/* Engine-verified puzzles (generated by brute-force + verification).
   type 'mate' = deliver checkmate (any mating move accepted).
   type 'move' = play a verified key move (from-to). sol holds accepted moves.
   To expand later: add tactics from a larger DB; format unchanged. */
var PUZZLES=[
 {fen:"8/1Q6/8/8/8/4K3/8/4k3 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/4Q3/8/8/8/8/k1K5/8 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/8/1Q6/8/3K4/8/3k4 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"k1K5/8/8/8/8/1Q6/8/8 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/8/8/2Q5/7K/8/7k w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/8/8/6Q1/8/7k/5K2 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"k7/2K5/8/8/2Q5/8/8/8 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/8/Q7/8/6K1/8/6k1 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/5K1k/8/8/4R3/8/8 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/8/8/5K1k/8/3R4/8 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/k1K5/8/1R6/8/8/8 w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},
 {fen:"8/8/8/5R2/8/7K/8/7k w - - 0 1", diff:"Easy", type:"mate", goal:"Mate in 1", sol:null, desc:"Checkmate in one."},

 {fen:"4K3/7k/8/8/8/8/8/6Q1 w - - 0 1", diff:"Medium", type:"move", goal:"Mate in 2 (find the key move)", sol:["e8f7"], desc:"Forces checkmate in two."},
 {fen:"6k1/8/8/5K2/5Q2/8/8/8 w - - 0 1", diff:"Medium", type:"move", goal:"Mate in 2 (find the key move)", sol:["f5g6"], desc:"Forces checkmate in two."},
 {fen:"k7/3Q4/8/2K5/8/8/8/8 w - - 0 1", diff:"Medium", type:"move", goal:"Mate in 2 (find the key move)", sol:["c5b6","c5c6"], desc:"Forces checkmate in two."},
 {fen:"5k2/8/8/7K/4Q3/8/8/8 w - - 0 1", diff:"Medium", type:"move", goal:"Mate in 2 (find the key move)", sol:["h5g6"], desc:"Forces checkmate in two."},
 {fen:"8/8/1Q6/8/3K4/8/8/k7 w - - 0 1", diff:"Medium", type:"move", goal:"Mate in 2 (find the key move)", sol:["d4c3"], desc:"Forces checkmate in two."},
 {fen:"4Q3/8/8/8/8/7K/8/5k2 w - - 0 1", diff:"Medium", type:"move", goal:"Mate in 2 (find the key move)", sol:["h3g3"], desc:"Forces checkmate in two."},

 {fen:"K7/6N1/7q/8/7k/8/8/8 w - - 0 1", diff:"Hard", type:"move", goal:"Win the queen with a fork", sol:["g7f5"], desc:"Knight forks king and queen."},
 {fen:"K7/5q2/8/8/4k3/5N2/8/8 w - - 0 1", diff:"Hard", type:"move", goal:"Win the queen with a fork", sol:["f3g5"], desc:"Knight forks king and queen."},
 {fen:"7K/8/8/4N3/5q2/8/1k6/8 w - - 0 1", diff:"Hard", type:"move", goal:"Win the queen with a fork", sol:["e5d3"], desc:"Knight forks king and queen."},
 {fen:"8/8/1k1q4/8/8/8/1N6/7K w - - 0 1", diff:"Hard", type:"move", goal:"Win the queen with a fork", sol:["b2c4"], desc:"Knight forks king and queen."},
 {fen:"7K/4q3/8/8/1k3N2/8/8/8 w - - 0 1", diff:"Hard", type:"move", goal:"Win the queen with a fork", sol:["f4d5"], desc:"Knight forks king and queen."},
 {fen:"K7/8/3q4/8/8/8/3N1k2/8 w - - 0 1", diff:"Hard", type:"move", goal:"Win the queen with a fork", sol:["d2e4"], desc:"Knight forks king and queen."}
];
